[program:djangoblog-web]
directory=/root/project/djangoblog
command=/bin/bash /root/project/djangoblog/scripts/start_web.sh
environment=DJANGOBLOG_ENV_FILE="/root/project/djangoblog/.env",DJANGOBLOG_PROJECT_DIR="/root/project/djangoblog"
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/djangoblog-web.log
stderr_logfile=/var/log/supervisor/djangoblog-web.err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[program:djangoblog-scheduler]
directory=/root/project/djangoblog
command=/bin/bash /root/project/djangoblog/scripts/start_scheduler.sh
environment=DJANGOBLOG_ENV_FILE="/root/project/djangoblog/.env",DJANGOBLOG_PROJECT_DIR="/root/project/djangoblog"
autostart=true
autorestart=true
startsecs=5
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/djangoblog-scheduler.log
stderr_logfile=/var/log/supervisor/djangoblog-scheduler.err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_backups=5

[group:djangoblog]
programs=djangoblog-web,djangoblog-scheduler
