# Generated by Django 5.2.13 on 2026-05-12 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('reason', models.TextField(blank=True, default='', verbose_name='推荐理由')),
                ('source', models.CharField(choices=[('aihot', 'AI HOT'), ('tech', '技术站点')], default='aihot', max_length=50, verbose_name='来源')),
                ('source_name', models.CharField(blank=True, default='', max_length=120, verbose_name='来源名称')),
                ('source_url', models.URLField(max_length=700, unique=True, verbose_name='原文链接')),
                ('tags', models.CharField(blank=True, default='', max_length=300, verbose_name='标签')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='抓取时间')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='idx_news_source_pub'), models.Index(fields=['is_visible', '-fetched_at'], name='idx_news_visible_fetch')],
            },
        ),
    ]
